main:
  - name: About
    url: "#about"
    weight: 1
  - name: Services
    url: "#services"
    weight: 2
  - name: Posts
    url: "#posts"
    weight: 3
  - name: Testimonials
    url: "#testimonials"
    weight: 4
  - name: Contact
    url: "#contact"
    weight: 5
