# local_backend: true
backend:
  name: git-gateway
  branch: main
media_folder: assets/media
public_folder: /media
site_url: 'https://www.channelmotions.com'
editor:
  preview: false
  frame: false
  size: half
collections:
  - name: authors
    label: Authors
    label_singular: Author
    folder: content/authors
    path: '{{slug}}/_index'
    filter:
      field: cms_exclude
    create: true
    fields:
      - label: Display name (such as your full name)
        name: title
        widget: string
      - label: Position or tagline (such as Professor of AI)
        name: role
        widget: string
        required: false
      - label: Avatar (upload an image named `avatar.jpg/png`)
        name: avatar_filename
        widget: image
        default: avatar
        required: false
        media_library:
          config:
            multiple: false
      - label: Short biography (shown in author boxes)
        name: bio
        widget: string
        required: false
      - label: Full biography (shown in About widget)
        name: body
        widget: markdown
        required: false
      - label: Interests (shown in About widget)
        name: interests
        required: false
        widget: list
        fields:
          - name: interest
            label: Interest
            widget: string
            requrited: false
      - label: Social links
        name: social
        required: false
        widget: list
        fields:
          - label: Link
            name: link
            widget: string
          - label: Icon pack
            name: icon_pack
            widget: select
            multiple: false
            options:
              - label: None
                value: ''
              - label: Solid
                value: fas
              - label: Regular
                value: far
              - label: Brand
                value: fab
              - label: Academic
                value: ai
          - label: >-
              Icon (see
              https://docs.hugoblox.com/getting-started/page-builder/#icons)
            name: icon
            widget: string
          - label: Label (tooltip)
            name: label
            widget: string
            required: false
          - label: Display in About widget and...
            name: display
            widget: object
            fields:
              - label: Header (main menu)
                name: header
                widget: boolean
                default: false
                required: false
      - label: >-
          Organizations you belong to or are affiliated with (shown in About
          widget)
        name: organizations
        required: false
        widget: list
        fields:
          - label: Organization
            name: name
            widget: string
            required: true
          - label: Link
            name: url
            widget: string
            required: false
      - label: Education
        name: education
        required: false
        widget: object
        fields:
          - label: Courses
            name: courses
            required: false
            widget: list
            fields:
              - label: Course
                name: course
                widget: string
                required: true
              - label: Institution
                name: institution
                widget: string
                required: true
              - label: Year
                name: year
                widget: number
                value_type: int
                required: false
      - label: Email (to use a Gravatar.com avatar)
        name: email
        widget: string
        required: false
      - label: Super user (is this the primary site user?)
        name: superuser
        widget: boolean
        default: false
      - label: User groups (only for organization websites)
        name: user_groups
        required: false
        widget: list
  - name: posts
    label: Posts
    label_singular: Post
    folder: content/post
    path: '{{slug}}/index'
    filter:
      field: cms_exclude
    create: true
    editor:
      preview: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Subtitle
        name: subtitle
        widget: string
        required: false
      - label: Body
        name: body
        widget: markdown
      - label: Publish this page on
        name: date
        widget: datetime
      - label: Summary
        name: summary
        widget: markdown
        required: false
      - label: Draft
        name: draft
        widget: boolean
        default: false
        required: false
      - label: Featured
        name: featured
        widget: boolean
        default: false
        required: false
      - label: Authors
        name: authors
        required: false
        widget: list
      - label: Tags
        name: tags
        required: false
        widget: list
      - label: Categories
        name: categories
        required: false
        widget: list
      - label: Projects
        name: projects
        required: false
        widget: list
      - label: Featured Image
        name: image
        required: false
        widget: object
        fields:
          - label: Upload an image named `featured.jpg/png`
            name: filename
            widget: image
            default: featured
            required: false
            media_library:
              config:
                multiple: false
          - label: Caption
            name: caption
            widget: string
            required: false
          - label: Description for screen readers
            name: alt_text
            widget: string
            required: false
          - label: >-
              Where's the focal point in the image? Smart, Center, TopLeft, Top,
              TopRight, Left, Right, BottomLeft, Bottom, BottomRight.
            name: focal_point
            widget: string
            required: false
            default: Smart
          - label: Thumbnail Only?
            name: preview_only
            widget: boolean
            default: false
            required: false
  - name: pages
    label: Pages
    files:
      - file: content/privacy.md
        label: Privacy Policy
        name: privacy
        fields:
          - label: Title
            name: title
            widget: string
          - label: Publish Date
            name: date
            widget: datetime
          - label: Subtitle
            name: subtitle
            widget: string
            required: false
          - label: Summary
            name: summary
            widget: markdown
            required: false
          - label: Draft
            name: draft
            required: false
            widget: boolean
            default: false
          - label: Body
            name: body
            widget: markdown
      - file: content/terms.md
        label: Terms
        name: terms
        fields:
          - label: Title
            name: title
            widget: string
          - label: Publish Date
            name: date
            widget: datetime
          - label: Subtitle
            name: subtitle
            widget: string
            required: false
          - label: Summary
            name: summary
            widget: markdown
            required: false
          - label: Draft
            name: draft
            required: false
            widget: boolean
            default: false
          - label: Body
            name: body
            widget: markdown
      - file: content/_index.md
        label: Homepage
        name: home
        fields:
          - label: Sections
            label_singular: Section
            name: sections
            widget: list
            collapsed: true
            type_key: block
            types:
              - name: about.biography
                label: About
                widget: object
                summary: 'Author: {{fields.content.title}}'
                fields:
                - name: id
                  label: Unique Id
                  widget: string
                  default: about
                  hint: An id, a preferable lower cased string, that is unique throughout the homepage
                - name: content
                  widget: object
                  label: Content
                  fields:
                    - name: title
                      label: "Titel"
                      widget: string
                      default: Biography
                    - name: username
                      label: Author
                      hint: Username of an Author from Authors collection to be presented here e.g. 'admin'
                      widget: string
                      default: admin
              - name: testimonials
                label: Testimonials
                widget: object
                summary: 'Testimonials'
                fields:
                - name: id
                  label: Unique Id
                  widget: string
                  default: testimonials
                  hint: An id, a preferable lower cased string, that is unique throughout the homepage
                - name: content
                  widget: object
                  label: Content
                  fields:
                    - name: title
                      label: "Titel"
                      widget: string
                      default: Testimonials
                    - name: subtitle
                      label: Subtitle
                      widget: string
                      required: false
                    - name: items
                      label: Testimonials
                      label_singular: Testimonial
                      widget: list
                      fields:
                        - name: name
                          label: Name
                          widget: string
                        - name: text
                          label: Text
                          widget: text
              - name: contact
                label: Contact
                widget: object
                summary: 'Contact Information'
                fields:
                - name: id
                  label: Unique Id
                  widget: string
                  default: contact
                  hint: An id, a preferable lower cased string, that is unique throughout the homepage
                - name: content
                  widget: object
                  label: Content
                  fields:
                    - name: title
                      label: "Titel"
                      widget: string
                      default: Contact
                    - name: text
                      label: Text
                      hint: Text above the form
                      widget: string
                      required: false
                    - name: email
                      label: "Email"
                      widget: string
                      default: bob@channelmotions.com
                      required: false
                    - name: phone
                      label: "Phone"
                      widget: string
                      default: 617 470 7713
                      required: false
                    - name: office_hours
                      label: "Office Hours"
                      hint: "A simple list of strings e.g.: Mon 09:00 am - 05:00 pm"
                      widget: list
                      default:
                        - 'Weekdays 09:00 am to 05:00 pm'
                        - 'Saturday and Monday closed'
                      required: false
                      fields:
                        - name: hours
                          label: Hours
                          widget: string
                    - name: appointment_url
                      label: Appointment Url
                      hint: Url to your appointment calendar like calendly
                      widget: string
                      default: https://calendly.com
                      required: false
              - name: features
                label: Features
                widget: object
                summary: 'Feature Block: {{fields.content.title}} '
                hint: 'Can be used to display things like services, product features or capabilities'
                fields:
                - name: id
                  label: Unique Id
                  widget: string
                  default: services
                  hint: An id, a preferable lower cased string, that is unique throughout the homepage
                - name: content
                  widget: object
                  label: Content
                  fields:
                    - name: title
                      label: "Title"
                      widget: string
                      default: Services
                      required: false
                    - name: subtitle
                      label: "Subtitle"
                      widget: string
                      requrited: false
                    - name: text
                      label: Text
                      widget: text
                      required: false
                    - name: items
                      label: "Items"
                      label_singular: "Item"
                      hint: "Examples: Features of a proudct, services, capabiletes, ..."
                      widget: list
                      summary: '{{fields.name}}'
                      fields:
                        - name: name
                          label: Name
                          widget: string
                        - name: description
                          label: Description
                          widget: text
                        - name: icon
                          label: icon
                          widget: string
                          hint: 'Id of an icon from a icon pack/library like http://fontawesome.com'
                        - name: icon_pack
                          label: Icon Pack'
                          widget: string
                          hint: 'Specify the icon pack/library that the icon contains'
              - name: collection
                label: Collection
                widget: object
                summary: 'Posts Collection: {{fields.content.title}}'
                fields:
                - name: id
                  label: Unique Id
                  widget: string
                  default: posts
                  hint: An id, a preferable lower cased string, that is unique throughout the homepage
                - name: content
                  widget: object
                  label: Content
                  fields:
                    - name: title
                      label: "Titel"
                      widget: string
                      default: 'Recent Posts'
  - name: config
    label: 'Website Configuration'
    files:
      - name: navigation
        file: config/_default/menus.yaml
        label: 'Navigation'
        
        fields:
          - name: main
            label: Main Navigation
            label_singular: Main Navigation Item
            widget: list
            collapsed: true 
            fields:
              - name: name
                label: 'Name'
                hint: 'Name of the navigation item that gets displayed to the user'
                widget: string
              - name: url
                label: 'Url'
                hint: 'Absolute (e.g. https://exemple.com/page.html) or relative (e.g. ../page.html) url or anchor link (like /#contact or ./#contact).'
                widget: string 
              - name: weight
                label: Weight
                hint: 'The Navigation is sorted by this number'
                widget: hidden






